language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - yarn

script:
  - yarn build

after_script:
  - cd dist && git init && git config user.name "weineel" && git config user.email "LiJF_wn@163.com" && git add . && git commit -m "Update Website" && git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/weineel/frontend-sprint.git
